### PR TITLE
fix: SDK versioning policy update

### PR DESCRIPTION
**Pull request by richard-bogdan-bitrise**
Step will use latest versions by default.

APM-2394

### CODE REVIEW

**Review by daniellevass-bitrise — APPROVED** [review]
I didn't know about the "+" thing - will that work in our docs too?

**Comment by richard-bogdan-bitrise** [comment]
Sorry, I am a bit lost. Which docs are you referring to?

**Comment by daniellevass-bitrise** [comment]
Our installation instructions that have people write "latestVersion" and get Android Studio to correct it to the latest version - can we just use `implementation("io.bitrise.trace:trace-sdk:+")` like you have here?

**Comment by daniellevass-bitrise** [comment]
I guess not because Android Studio gives the same warning:

Screenshot 2021-02-08 at 15 55 54

**Comment by richard-bogdan-bitrise** [comment]
We can, but it is generally discouraged. I think we should encourage people to explicitly set the version.

**Pull request merged**
