### PR TITLE
fix: Path issue

### PR DESCRIPTION
**Pull request by richard-bogdan-bitrise**
Fixed path issue for default "project_path" step input.

APM-2418

### CODE REVIEW

**Review by daniellevass-bitrise — CHANGES_REQUESTED** [review]
Hi,

As we've had a lot of issues in the past few weeks with not properly testing code we're pushing to production I would like screenshots/links to this working with a "typical" app setup (one app in the repo) and the mono repo before reviewing any code changes. 

Please let me know if you have any issues with this.

**Comment by richard-bogdan-bitrise** [comment]
Please check these builds:
[https://app.bitrise.io/app/3c8a6c5f34b89676#/builds](https://app.bitrise.io/app/3c8a6c5f34b89676#/builds)
and
[https://app.bitrise.io/app/4326f8f4c4d6eda6#/builds](https://app.bitrise.io/app/4326f8f4c4d6eda6#/builds)

There is a workflow primary (without trace step), and there is one called trace (with trace step).

**Comment by daniellevass-bitrise** [comment]
> Please check these builds:
> https://app.bitrise.io/app/3c8a6c5f34b89676#/builds
> and
> https://app.bitrise.io/app/4326f8f4c4d6eda6#/builds
> 
> There is a workflow primary (without trace step), and there is one called trace (with trace step).

Hi, I get 404's for both of them - can you check they're part of the trace-monitoring group?

**Comment by richard-bogdan-bitrise** [comment]
> > Please check these builds:
> > https://app.bitrise.io/app/3c8a6c5f34b89676#/builds
> > and
> > https://app.bitrise.io/app/4326f8f4c4d6eda6#/builds
> > There is a workflow primary (without trace step), and there is one called trace (with trace step).
> 
> Hi, I get 404's for both of them - can you check they're part of the trace-monitoring group?

Sent a DM n slack to resolve access issues.

**Comment by daniellevass-bitrise** [comment]
> > > Please check these builds:
> > > https://app.bitrise.io/app/3c8a6c5f34b89676#/builds
> > > and
> > > https://app.bitrise.io/app/4326f8f4c4d6eda6#/builds
> > > There is a workflow primary (without trace step), and there is one called trace (with trace step).
> > 
> > 
> > Hi, I get 404's for both of them - can you check they're part of the trace-monitoring group?
> 
> Sent a DM in slack to resolve access issues.

to unblock this while i'm waiting on access- can you please explain what the two builds were actually testing? and maybe post screenshots of the build passing with this particular version of the step?

**Comment by richard-bogdan-bitrise** [comment]
Sure, simple Android builds with the add-trace-sdk-android step added.
Screenshot 2021-02-15 at 15 54 51
Screenshot 2021-02-15 at 15 55 13
Screenshot 2021-02-15 at 15 55 41
Screenshot 2021-02-15 at 15 55 57

**Comment by daniellevass-bitrise** [comment]
> Sure, simple Android builds with the add-trace-sdk-android step added.
> Screenshot 2021-02-15 at 15 54 51
> Screenshot 2021-02-15 at 15 55 13
> Screenshot 2021-02-15 at 15 55 41
> Screenshot 2021-02-15 at 15 55 57

and the other one? Do we have a test workflow for the mono repo example - where there are multiple apps/projects in the same folder?

**Comment by richard-bogdan-bitrise** [comment]
> > Sure, simple Android builds with the add-trace-sdk-android step added.
> 
> and the other one? Do we have a test workflow for the mono repo example - where there are multiple apps/projects in the same folder?

What do you mean? I added screenshots for both apps, sample-ship-addon and sample-apps-monorepo.

**Comment by daniellevass-bitrise** [comment]
> > > Sure, simple Android builds with the add-trace-sdk-android step added.
> > 
> > 
> > and the other one? Do we have a test workflow for the mono repo example - where there are multiple apps/projects in the same folder?
> 
> What do you mean? I added screenshots for both apps, sample-ship-addon and sample-apps-monorepo.

Sure, i get you posted the workflow but that doesn't tell me anything about the source code it's being applied to - you posted two build links but only wrote text about one? What does the other build do?

**Comment by richard-bogdan-bitrise** [comment]
Here are the sources for the two given app:
1. [https://github.com/bitrise-io/sample-apps-monorepo](https://github.com/bitrise-io/sample-apps-monorepo)
2. [https://github.com/bitrise-io/sample-ship-addon-android](https://github.com/bitrise-io/sample-ship-addon-android)

Picture 1 and 3 belongs to sample-ship-addon-android (build summary, and workflow)
Picture 2 and 4 belongs to sample-apps-monorepo (build summary, and workflow)

**Comment by daniellevass-bitrise** [comment]
> Here are the sources for the two given app:
> 
> 1. https://github.com/bitrise-io/sample-apps-monorepo
> 2. https://github.com/bitrise-io/sample-ship-addon-android
> 
> Picture 1 and 3 belongs to sample-ship-addon-android (build summary, and workflow)
> Picture 2 and 4 belongs to sample-apps-monorepo (build summary, and workflow)

thank you for explaining - it's very difficult to follow what's happening when you don't have access to half the things - being more explicit is always better than assuming someone knows something :)

**Review by daniellevass-bitrise — APPROVED** [review]

**Comment by richard-bogdan-bitrise** [comment]
No worries, I was just a bit confused that I am misunderstanding something. 🙂

**Pull request merged**
